<?php /** @var $this \NetBricks\Page\Component\Widget\Management  */ ?>
<div <?php echo $this->renderDefaultAttributes(); ?>>

    <div class="widget_container">
        <?php foreach ($this->getDataProvider() as $widget): ?>
        <div class="widget_selector">
            <?php echo $this->createWidget($widget['type']); ?>
        </div>
        <?php endforeach; ?>
    </div>

    <a href="#" class="add_widget">Add widget</a>

</div>