<?php /** @var $this \NetBricks\Common\Component\Extended\ArrayBuilder\ArrayBuilder */ ?>
<div <?php echo $this->renderTagAttributes($this->getDefaultAttributes()); ?>
        data-name="<?php echo $this->getName(); ?>">

    <ul class="array_builder_list">

    </ul>

    <div class="array_builder_form">
        <input type="text" class="array_builder_text">
        <a href="#" class="array_builder_add_button">+</a>
    </div>

</div>